version: "3.4"
name: movies
services:
  db:
    image: mariadb:11.3.2
    container_name: movies-db-dev
    environment:
      MYSQL_DATABASE: movies
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d