services:
  db:
    image: mariadb:11.3.2
    container_name: movies-db
    environment:
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'rootpassword'
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    networks:
      - network1

  backend:
    build: ./backend
    container_name: movies-api
    ports:
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - network1

  frontend:
    build: ./frontend
    container_name: movies-ui
    ports:
      - "1234:1234"
    networks:
      - network1

networks:
  network1:
    driver: bridge