version: '3.8'

services:
  db:
    image: mariadb:11.3.2
    container_name: movies-db-dev
    environment:
      MYSQL_DB: moviesdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

